"""initial_schema

Revision ID: b7430513a0b0
Revises: 
Create Date: 2026-09-29 16:47:34.790081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hindi_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=50), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_table_number'), 'tables', ['table_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('assigned_station', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dining_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('table_id', sa.String(length=50), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dining_sessions_created_at'), 'dining_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_dining_sessions_status'), 'dining_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_dining_sessions_table_id'), 'dining_sessions', ['table_id'], unique=False)
    op.create_index('uq_table_open_session', 'dining_sessions', ['table_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('menu_items',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_veg', sa.Boolean(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('popular', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('add_ons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_name'), 'menu_items', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('cafe_id', sa.String(length=100), nullable=False),
    sa.Column('table_id', sa.String(length=50), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.Column('dining_session_id', sa.String(length=50), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_mobile', sa.String(length=20), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='PLACED', nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dining_session_id'], ['dining_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_dining_session_id'), 'orders', ['dining_session_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_session_token'), 'orders', ['session_token'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('dining_session_id', sa.String(length=50), nullable=True),
    sa.Column('bill_type', sa.String(length=50), server_default='SESSION', nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_rate', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dining_session_id'], ['dining_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_dining_session_id'), 'billing_invoices', ['dining_session_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_invoice_number'), 'billing_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_billing_invoices_order_id'), 'billing_invoices', ['order_id'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('menu_item_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_total', sa.Float(), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=True),
    sa.Column('selected_add_ons', sa.JSON(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_billing_invoices_order_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_invoice_number'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_dining_session_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_session_token'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_dining_session_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_items_name'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_dining_sessions_table_id'), table_name='dining_sessions')
    op.drop_index('uq_table_open_session', table_name='dining_sessions')
    op.drop_index(op.f('ix_dining_sessions_status'), table_name='dining_sessions')
    op.drop_index(op.f('ix_dining_sessions_created_at'), table_name='dining_sessions')
    op.drop_table('dining_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tables_table_number'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('categories')
    op.drop_table('cafe_settings')
    # ### end Alembic commands ###
