"""add round_off to orders and billing_invoices

Revision ID: 76349d713e21
Revises: a32d153ff808
Create Date: 2026-10-02 12:04:50.428676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76349d713e21'
down_revision: Union[str, Sequence[str], None] = 'a32d153ff808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('round_off', sa.Float(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('round_off', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'round_off')
    op.drop_column('billing_invoices', 'round_off')
    # ### end Alembic commands ###
