"""add_cancellation_fields_to_orders

Revision ID: 8d495ed40ef5
Revises: 76349d713e21
Create Date: 2026-10-05 16:59:03.619183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d495ed40ef5'
down_revision: Union[str, Sequence[str], None] = '76349d713e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancellation_note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancellation_note')
    op.drop_column('orders', 'cancellation_reason')
    # ### end Alembic commands ###
