"""add extra_charge to orders and billing_invoices

Revision ID: a32d153ff808
Revises: 0002_add_contact_number
Create Date: 2026-10-01 11:20:35.038174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32d153ff808'
down_revision: Union[str, Sequence[str], None] = '0002_add_contact_number'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_invoices', sa.Column('extra_charge', sa.Float(), server_default='0', nullable=False))
    op.drop_index(op.f('uq_table_open_session'), table_name='dining_sessions', postgresql_where="((status)::text = 'OPEN'::text)")
    op.add_column('orders', sa.Column('extra_charge', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'extra_charge')
    op.create_index(op.f('uq_table_open_session'), 'dining_sessions', ['table_id'], unique=True, postgresql_where="((status)::text = 'OPEN'::text)")
    op.drop_column('billing_invoices', 'extra_charge')
    # ### end Alembic commands ###
